name: dev
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - autograd=1.3
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.3
  - bokeh=2.0.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - chart-studio=1.0.0
  - colorlover=0.3.0
  - cryptography=2.8
  - cufflinks-py=0.17.3
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dill=0.3.1.1
  - dnspython=1.16.0
  - entrypoints=0.3
  - freetype=2.10.1
  - future=0.18.2
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.5.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.0.1
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab_server=1.0.7
  - kiwisolver=1.1.0
  - libcxx=9.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libuv=1.34.0
  - lifetimes=0.11.1
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - nodejs=13.10.1
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - plotly=4.6.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pymongo=3.9.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.8.2
  - python-cufflinks=0.17.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - readline=8.0
  - requests=2.23.0
  - retrying=1.3.3
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.1
  - six=1.14.0
  - sqlite=3.30.1
  - stripe=2.36.2
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - airtable==0.3.1
    - cachetools==4.1.0
    - google-api-core==1.17.0
    - google-api-python-client==1.8.2
    - google-auth==1.14.1
    - google-auth-httplib2==0.0.3
    - googleapis-common-protos==1.51.0
    - httplib2==0.17.3
    - oauth2client==4.1.3
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - rsa==4.0
    - uritemplate==3.0.1
prefix: /Users/Kyle/opt/anaconda3/envs/dev

